# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-26 04:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webchat', '0002_auto_20170526_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
    ]
